"""
pdf_export.py - PDF generation utility for Allergy-Safe Meal Planner using fpdf2
"""

from typing import List, Dict, Any, Set
from fpdf import FPDF

def clean_pdf_text(text: str) -> str:
    """Sanitize unicode emojis, smart punctuation and non-latin1 characters for PDF rendering."""
    if not isinstance(text, str):
        text = str(text)
    
    # Strip common emojis and non-standard symbols
    emojis_and_symbols = [
        "🥬", "🍗", "🥛", "🌾", "🥜", "🧂", "🥣", "🥗", "🍲", "⏱️", "👨‍🍳",
        "🚫", "✅", "🛡️", "🟢", "⚡", "", "🔒", "📋", "📦", "📄", "🎉",
        "✨", "🗓️", "🛒", "🔄", "⚙️", "💡", "🔍", "⏱"
    ]
    for sym in emojis_and_symbols:
        text = text.replace(sym, "")
    
    # Replace smart quotes and dashes with standard ASCII
    replacements = {
        "’": "'", "‘": "'", "“": '"', "”": '"',
        "—": "-", "–": "-", "•": "-", "…": "..."
    }
    for orig, rep in replacements.items():
        text = text.replace(orig, rep)
        
    return text.encode("latin-1", "replace").decode("latin-1").strip()

class AllergySafePDF(FPDF):
    def __init__(self, title_header: str = "Allergy-Safe Meal Planner"):
        super().__init__(orientation="P", unit="mm", format="A4")
        self.title_header = clean_pdf_text(title_header)
        self.set_auto_page_break(auto=True, margin=15)

    def header(self):
        self.set_font("helvetica", "B", 14)
        self.set_text_color(30, 41, 59)
        self.cell(self.epw, 8, self.title_header, new_x="LMARGIN", new_y="NEXT", align="C")
        self.set_draw_color(168, 85, 247)
        self.set_line_width(0.5)
        self.line(self.l_margin, self.get_y(), self.w - self.r_margin, self.get_y())
        self.ln(4)

    def footer(self):
        self.set_y(-12)
        self.set_font("helvetica", "I", 8)
        self.set_text_color(148, 163, 184)
        self.cell(self.epw, 8, f"Page {self.page_no()} | Generated by Allergy-Safe Meal Planner | 100% Allergen Safe", align="C")

def generate_shopping_list_pdf(
    friend_name: str, 
    allergies: List[str], 
    categorized_items: Dict[str, List[str]], 
    checked_items: Set[str] = None
) -> bytes:
    """Generate a clean, professional, aisle-categorized PDF grocery list."""
    checked = checked_items or set()
    pdf = AllergySafePDF(title_header=f"Grocery Shopping List - {friend_name}")
    pdf.add_page()

    # Meta banner
    pdf.set_fill_color(243, 232, 255) # Light purple
    pdf.set_draw_color(192, 132, 252)
    pdf.set_text_color(88, 28, 135)
    pdf.set_font("helvetica", "B", 10)
    
    allergies_clean = clean_pdf_text(", ".join(allergies) if allergies else "None")
    banner_text = f"Strict Allergen Exclusions: {allergies_clean}"
    pdf.cell(pdf.epw, 8, banner_text, border=1, fill=True, new_x="LMARGIN", new_y="NEXT", align="L")
    pdf.ln(4)

    # Render Aisle Sections
    for cat_name, items in categorized_items.items():
        if not items:
            continue
        
        clean_cat = clean_pdf_text(cat_name)
        pdf.set_fill_color(241, 245, 249) # Slate light
        pdf.set_text_color(30, 41, 59)
        pdf.set_font("helvetica", "B", 11)
        pdf.cell(pdf.epw, 7, f"  {clean_cat}", border="B", fill=True, new_x="LMARGIN", new_y="NEXT")
        pdf.ln(1)

        pdf.set_font("helvetica", size=9)
        for itm in items:
            is_chk = itm in checked
            chk_box = "[X]" if is_chk else "[  ]"
            clean_itm = clean_pdf_text(itm)
            if is_chk:
                pdf.set_text_color(100, 116, 139) # Muted checked
            else:
                pdf.set_text_color(15, 23, 42)
            pdf.cell(pdf.epw, 6, f"    {chk_box}  {clean_itm}", new_x="LMARGIN", new_y="NEXT")

        pdf.ln(3)

    return bytes(pdf.output())

def generate_meal_plan_pdf(
    friend_name: str,
    allergies: List[str],
    preferences: str,
    plan: Dict[str, Any]
) -> bytes:
    """Generate a publication-quality complete meal plan PDF reflecting selected days."""
    days = plan.get("days", [])
    days_count = len(days)
    days_text = f"{days_count}-Day " if days_count > 0 else ""
    pdf = AllergySafePDF(title_header=f"Allergy-Safe {days_text}Meal Plan - {friend_name}")
    pdf.add_page()

    # Meta banner
    pdf.set_fill_color(243, 232, 255)
    pdf.set_draw_color(192, 132, 252)
    pdf.set_text_color(88, 28, 135)
    pdf.set_font("helvetica", "B", 10)
    allergies_clean = clean_pdf_text(", ".join(allergies) if allergies else "None")
    pdf.cell(pdf.epw, 8, f"Strict Exclusions: {allergies_clean}", border=1, fill=True, new_x="LMARGIN", new_y="NEXT", align="L")
    pdf.ln(2)

    if preferences:
        pdf.set_font("helvetica", "I", 9)
        pdf.set_text_color(71, 85, 105)
        pdf.multi_cell(w=pdf.epw, h=5, text=f"Dietary Preferences: {clean_pdf_text(preferences)}")
        pdf.ln(3)

    days = plan.get("days", [])
    for idx, day in enumerate(days):
        day_label = clean_pdf_text(day.get("day", f"Day {idx+1}"))
        
        # Day Header
        pdf.set_x(pdf.l_margin)
        pdf.set_fill_color(224, 231, 255) # Light indigo
        pdf.set_text_color(30, 27, 75)
        pdf.set_font("helvetica", "B", 11)
        pdf.cell(pdf.epw, 7, f"  {day_label}", fill=True, new_x="LMARGIN", new_y="NEXT")
        pdf.ln(1)

        for meal_key, label in [("breakfast", "Breakfast"), ("lunch", "Lunch"), ("dinner", "Dinner")]:
            meal = day.get(meal_key, {})
            name = clean_pdf_text(meal.get("name", label))
            time_str = clean_pdf_text(meal.get("prep_time", "15 mins"))
            desc = clean_pdf_text(meal.get("description", ""))
            ingredients = [clean_pdf_text(i) for i in meal.get("ingredients", [])]
            instructions = clean_pdf_text(meal.get("instructions", ""))
            chef_tip = clean_pdf_text(meal.get("chef_tip", ""))

            pdf.set_x(pdf.l_margin)
            pdf.set_font("helvetica", "B", 10)
            pdf.set_text_color(124, 58, 237)
            pdf.cell(24, 6, f"{label}:")
            pdf.set_text_color(15, 23, 42)
            pdf.cell(pdf.epw - 24, 6, f"{name} ({time_str})", new_x="LMARGIN", new_y="NEXT")

            if desc:
                pdf.set_x(pdf.l_margin)
                pdf.set_font("helvetica", "I", 8.5)
                pdf.set_text_color(100, 116, 139)
                pdf.multi_cell(w=pdf.epw, h=4.2, text=f"    {desc}")

            pdf.set_x(pdf.l_margin)
            pdf.set_font("helvetica", size=8.5)
            pdf.set_text_color(71, 85, 105)
            if ingredients:
                ing_str = "Ingredients: " + ", ".join(ingredients)
                pdf.multi_cell(w=pdf.epw, h=4.2, text=f"    {ing_str}")
            if instructions:
                pdf.set_x(pdf.l_margin)
                pdf.multi_cell(w=pdf.epw, h=4.2, text=f"    Prep Method: {instructions}")
            if chef_tip:
                pdf.set_x(pdf.l_margin)
                pdf.set_font("helvetica", "I", 8)
                pdf.set_text_color(180, 83, 9) # Amber
                pdf.multi_cell(w=pdf.epw, h=4.2, text=f"    Chef Tip: {chef_tip}")
            pdf.ln(1)

        pdf.ln(2)


    return bytes(pdf.output())
